// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not configured. Run `flutterfire configure` to enable it.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Platform not configured. Run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM62arv_gP9JWNbkUz8qCuHrBbOg5Coco',
    appId: '1:484913466979:android:bd56b2f0967e556bea3256',
    messagingSenderId: '484913466979',
    projectId: 'catatan-harian-project',
    storageBucket: 'catatan-harian-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP0T8cpjsYbK-VgxJBBr8Fyk2c7Zk3NJ0',
    appId: '1:484913466979:ios:87da8b012a0c5576ea3256',
    messagingSenderId: '484913466979',
    projectId: 'catatan-harian-project',
    storageBucket: 'catatan-harian-project.firebasestorage.app',
    iosBundleId: 'com.kelompok6.dailyJournalApp',
  );

}